database: "main.db"

host: "localhost"

port: 6969

shards:
    - id: 0
      name: "shard0"
      host: "127.0.0.1"
      port: 6969

    - id: 1
      name: "shard1"
      host: "127.0.0.1"
      port: 6868
